### ISSUE TITLE
Generate some ascii art for all the scripts to make them interesting.

### ISSUE THREAD

**Issue by rishavnandi** [rishavnandi/Boiler_Plates#10]
Currently the scripts are pretty boring, create some ascii art for them, could be anything but having an appropriate title as the ascii art would be the best.

**Comment by subhans11** [comment]
Do we need to create the ascii art **in the shell file?** or the ascii art should be generated **after running** the shell file?

we can use the **figlet** for generating the ascii art after running the shell file.

```
# ascii art

apt install figlet
figlet hello world
```

output - 
![figlet](https://user-images.githubusercontent.com/102163333/195265966-9da0cf25-bb1e-4387-af59-af5bbd44f2ed.PNG)

**Comment by rishavnandi** [comment]
@subhans11 Hi, I'm thinking about adding the ascii art to the top of the scripts just which might contain the title of the project and a link to the GitHub repo as I don't want this to rely on another dependency...the ascii art can be pretty simple which just shows the title of the project and the repo link that's all.
