### ISSUE TITLE
Update the images in README.md

### ISSUE THREAD

**Issue by rishavnandi** [rishavnandi/Boiler_Plates#15]
The radarr and sonarr apps now use dark themes using [theme.park](https://theme-park.dev/)

Update the documentation with the [updated images](https://drive.google.com/drive/folders/1nhAByxGxcfONNOOCC9AFRj5liTRZmlMn?usp=sharing)

**Comment by RohitShah1706** [comment]
@rishavnandi Please assign this issue to me. I am somewhat a newbie to open source.

**Comment by rishavnandi** [comment]
@RohitShah1706 Remember to go through the CONTRIBUTING.md and Follow general opensource PR practices.
